# Generated by Django 5.1.6 on 2025-03-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_borrow_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
